name: Deploy worker
on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Enable Yarn
        run: npm install -g yarn
        
      - name: Install Dependencies
        run: yarn install
        
      - name: Deploy with Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: yarn run wrangler publish

